### PR TITLE
perf: write files to repo outside of write lock

### LINKED ISSUE #7: files.ls ordering incorrect
Currently in js-ipfs master:

```
1) interface-ipfs-core over ipfs-api tests .files.ls should ls directory:

    Uncaught AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
    + expected - actual

     [
       {
         "hash": ""
    -    "name": "b"
    +    "name": "lv1"
         "size": 0
         "type": 0
       }
       {
         "hash": ""
    -    "name": "lv1"
    +    "name": "b"
         "size": 0
         "type": 0
       }
     ]
    
    at ipfs.files.ls (node_modules/interface-ipfs-core/js/src/files/ls.js:56:27)
    at transform (node_modules/ipfs-api/src/files/ls.js:8:3)
    at send (node_modules/ipfs-api/src/utils/send-request.js:217:7)
    at f (node_modules/once/once.js:25:25)
    at streamToValue (node_modules/ipfs-api/src/utils/stream-to-json-value.js:30:5)
    at concat (node_modules/ipfs-api/src/utils/stream-to-value.js:12:22)
    at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:37:43)
    at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

2) interface-ipfs-core over ipfs-api tests .files.ls should ls -l directory:

    Uncaught AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
    + expected - actual

     [
       {
    +    "hash": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn"
    +    "name": "lv1"
    +    "size": 0
    +    "type": 1
    +  }
    +  {
         "hash": "QmcZojhwragQr5qhTeFAmELik623Z21e3jBTpJXoQ9si1T"
         "name": "b"
         "size": 13
         "type": 0
       }
    -  {
    -    "hash": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn"
    -    "name": "lv1"
    -    "size": 0
    -    "type": 1
    -  }
     ]
    
    at ipfs.files.ls (node_modules/interface-ipfs-core/js/src/files/ls.js:76:27)
    at transform (node_modules/ipfs-api/src/files/ls.js:8:3)
    at send (node_modules/ipfs-api/src/utils/send-request.js:217:7)
    at f (node_modules/once/once.js:25:25)
    at streamToValue (node_modules/ipfs-api/src/utils/stream-to-json-value.js:30:5)
    at concat (node_modules/ipfs-api/src/utils/stream-to-value.js:12:22)
    at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:37:43)
    at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

### LINKED ISSUE #8: Test failures for files.read*Stream
Getting test failures in js-ipfs for the new `files.read*Stream` methods:

```
1) interface-ipfs-core tests .files.readReadableStream should not read not found, expect error:
   TypeError: stream.on is not a function
    at Context.it (node_modules/interface-ipfs-core/js/src/files/read-readable-stream.js:41:14)
    at process.topLevelDomainCallback (domain.js:121:23)

2) interface-ipfs-core tests .files.readReadableStream should read file:
   Error: Timeout of 40000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


3) interface-ipfs-core tests .files.readPullStream should not read not found, expect error:
   TypeError: read is not a function
    at next (node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (node_modules/pull-stream/sinks/drain.js:37:9)
    at pull (node_modules/pull-stream/pull.js:41:14)
    at Context.it (node_modules/interface-ipfs-core/js/src/files/read-pull-stream.js:40:7)
    at process.topLevelDomainCallback (domain.js:121:23)

4) interface-ipfs-core tests .files.readPullStream should read file:
   Error: Timeout of 40000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

### PR DESCRIPTION
**Pull request by achingbrain**
perf: read files from repo outside of read lock
feat: adds `-U` option to control `files.ls` sorting (for parity with ipfs/go-ipfs#5219) and fix #7
fix: standardise error messages with go
fix: make files.read*Stream methods return streams to fix #8

License: MIT
Signed-off-by: achingbrain <alex@achingbrain.net>

### CODE REVIEW

**Comment by achingbrain** [comment]
To illustrate the differences in performance, these graphs show the http throughput of `npm-on-ipfs`.  The red dots are requests to npm to download tarballs and json manifests, the blue dots are requests to the local IPFS daemon to store what we've downloaded from npm.

This is `ipfs-mfs@0.2.5` which performs read/write locking at the method level.  Note how there are long gaps between the blue dots as requests back up:

mfs-master

This is with writes to the ipfs repo performed outside of the write lock (e.g. we only calculate mfs tree hashes inside the write lock, actually writing blocks to disk is done outside allowing other operations to occur) - throughput is much improved:

mfs-write-interleaving

This is with reads from the ipfs repo performed outside of the read lock and with rate limiting applied to our daemon requests.  Average request time has come right down:

mfs-read-interleaving

The above are all installing [david-dm](https://www.npmjs.com/package/david) locally with no npm cache, a fresh ipfs repo with nothing in it and `npm-on-ipfs` eagerly downloading all tarballs of all versions of all dependencies.

**Comment by achingbrain** [comment]
The graphs are generated with [appmetrics-dash](https://www.npmjs.com/package/appmetrics-dash) in case anyone's interested.

**Comment by achingbrain** [comment]
Also, this is npm-on-ipfs performing the same set of operations against the go daemon:

mfs-go

**Comment by alanshaw** [comment]
I was just about to submit my review. It's ok because it was Approve 🥇 

Github errored, but I said something like, code looks sane and tests pass locally. I also linked it with js-ipfs and removed the `files.ls` and `files.read*Stream` tests skips and they all passed.

I'm very happy js-ipfs-mfs is at least as fast as go-ipfs-mfs!

**Pull request merged**
